### ISSUE TITLE
[Feature] Option to separate input bussed on the PA

### ISSUE THREAD

**Issue by XXxinsanityxX** [huneau/gregicality#9]
A feature like this has been implemented in GTNH, it allows the PA to be able to handle more that one shape or circuit by separating its input hatches.

Heres the GTNH commit to their version of GT5U if its of any use
https://github.com/GTNewHorizons/GT5-Unofficial/pull/249

**Comment by huneau** [comment]
is not the case by default ? I know it's the case for other multiblock but this one I forget.

**Comment by XXxinsanityxX** [comment]
Its somewhat working but not fully, an example would be have a PA with extruders in it and have two shapes on two diferent buses one to make plates and one to make gears, if you put ingots in the gear one but its not enough for the recipe to be done they will get turned into plates because the other bus with a plate shape can see them.

**Comment by huneau** [comment]
Yes, Its expected. 
If any recipe is found in each separate buses, then, Try to create a recipe with all buses

The issue here is: what happens if you decide to put multiple 1 slot bus on the multiblock?
You would like to create electrum, you make one bus for silver, one for gold... what am i supposed to do ?

**Comment by XXxinsanityxX** [comment]
Thid feature can be by default off and a button can be added in the PA GUI to turn on like the button the boiler GUI has.
